name = "honc-supercharger"
compatibility_date = "2024-08-27"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 4468

# [[kv_namespaces]]
# binding = "KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "R2"
bucket_name = "honc-supercharger-bucket"

[[d1_databases]]
binding = "DB"
database_name = "honc-supercharger"
database_id = "0d81a785-3c59-433e-8661-4ab4fe6df64f"
migrations_dir = "drizzle/migrations"

[ai]
binding = "AI"