name = "goosify"
compatibility_date = "2024-08-27"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "GOOSIFY_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "GOOSIFY_R2"
bucket_name = "goosify-bucket"

[[d1_databases]]
binding = "DB"
database_name = "goosify"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
migrations_dir = "drizzle/migrations"

[ai]
binding = "AI"